# config/packages/vich_uploader.yaml or app/config/config.yml
vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        recipe:
            uri_prefix: /images/recipe
            upload_destination: '%kernel.project_dir%/public/images/recipe'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer